version: '3.7'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/neo4j
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_maxSize=2G
      - NEO4J_dbms_memory_heap_initialSize=1G
      - NEO4J_apoc_import_file_enabled="true"
      - NEO4J_apoc_export_file_enabled="true"
      - NEO4J_apoc_import_file_use__neo4j__config="true"
      - NEO4J_apoc_export_file_use__neo4j__config="true"
      - NEO4J_PLUGINS=["apoc", "graph-algorithms", "graph-data-science"]
    volumes:
      - neo4j:/data

volumes:
  neo4j: