services:
  vector_db:
    image: "pgvector/pgvector:pg17"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
