version: '3'
services:
  mysql8:
    image: mysql:8.3.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - 33060:3306
    volumes:
      - data:/var/lib/mysql
    command:
      --max_allowed_packet=200M
      --lower_case_table_names=1

volumes:
  data:
