services:
  cc-xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: cc-xxl-job-admin
    restart: unless-stopped
    ports:
      - 18080:8080
    environment:
      TZ: Asia/Shanghai
      PARAMS: "--spring.datasource.url=jdbc:mysql://host.docker.internal:33060/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=root"
    volumes:
      - ./xxl-job/logs:/data/applogs
