version: '3.7'
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    ports:
      - 3001:3001
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  uptime-kuma-data:
    driver: local
