version: "3.7"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - data:/data

volumes:
  data: